monitor.alsa.rules = [
    {
        matches = [
            {
                node.name = "alsa_output.pci-0000_0b_00.4.pro-output-1"
            }
        ]
        actions = {
            update-props = {
                node.nick = "S/PDIF Output"
                node.pause-on-idle = false,
                session.suspend-timeout-seconds = 0,
                dither.noise = 2
            }
        }
    }
    {
        matches = [
            {
                node.name = "alsa_output.pci-0000_0b_00.4.pro-output-0"
            }
        ]
        actions = {
            update-props = {
                node.nick = "Headphones"
            }
        }
    }
]
