# Get IDs or classes with swaymsg -t get_tree
assign [app_id="org.mozilla.firefox"] 1
assign [app_id="thunderbird"] 1
assign [class="Spotify"] 1
assign [class="steam"] 2
assign [app_id="vesktop"] 3
assign [app_id="fluxer_app"] 3

for_window [app_id="gamescope"] allow_tearing yes
# for_window [class="steam_app_1022980"] allow_tearing yes # Ostranauts
for_window [title="DRG Mod Integration"] floating enable
